### ISSUE TITLE
Console font and cursor position.

### ISSUE THREAD

**Issue by jimschubert** [yankay/scala-tour#12]
Reported by Christian:

> The fonts are looking blurred, especially in the console (but in this comment form too), choose another font. The shadow of the console is a superfluous visual element. And there is a bug in the console: If I place the cursor after a certain character and insert a character, it is inserted one character too far to the right.

Probably a simple fix via window's resize event?

**Comment by yankay** [comment]
Hi. Sorry for the late reply.

I got the same issues when developing.
And it takes lots of time to deal with. I think it's the bug from "CodeMirror".
It can be used in screen bigger than 1024*800(Ipad). But for the smaller screen, the issues would happen.

Thank you
