### ISSUE TITLE
Proposed changes to Practice examples

### ISSUE THREAD

**Issue by jimschubert** [yankay/scala-tour#9]
I think the following changes to `Practice` default examples would be clearer or shorter:

**Extractor**  

```
import scala.util.matching.Regex

object Email {
  def unapply(str: String): Option[(String,String)] = 
    new Regex("""(.*)@(.*)""")
      .unapplySeq(str).get match {
      case user :: domain :: Nil => Some(user, domain)
      case _ => None
    }
}

"user@domain.com" match {
  case Email(user, domain) => println(user + "@" + domain)
}
```

In the above example, I think an explicit return type of `Option[(String,String)]` would make it more apparent what `unapply` does. Or, this could be clearer simply because `new Regex` is on the next line causing `unapply` and `unapplySeq` to separated?

**DSL**

```
import org.json4s.JsonDSL._
import org.json4s.jackson.JsonMethods.{pretty,render}
import java.util.Date

case class Twitter(id: Long, text: String, publishedAt: Option[java.util.Date])

var twitters = Twitter(1, "hello scala", Some(new Date())) ::
  Twitter(2, "I like scala tour", None) :: Nil

var json = ("twitters"
  -> twitters.map(
    t => ("id" -> t.id)
      ~ ("text" -> t.text)
      ~ ("published_at" -> t.publishedAt.toString())))

println(pretty(render(json)))
```

In the above example, I think the partial import makes it clearer that `pretty` and `render` are imports and not in `PreDef` like `println` or part of the DSL.

**Comment by yankay** [comment]
Hi Jim,
The 2 suggestion is very reasonable.
And I think it's good to change, I've Submit a Path to change them.
https://github.com/yankay/scala-tour/commits/master/webapp/index.html
